"""platform schema v2 — client, reference, portfolio, trading, performance, compliance

Hand-written (not autogenerated). Creates the multi-module schema that extends the
onboarding context. Onboarding tables in `public` are left untouched.

NOTE: ORM models currently exist only for the `client` schema (Client Master module).
Tables for the other modules are created here so the database is ready; their ORM
models will be added as each module is built. Until then, keep alembic autogenerate
from dropping these by adding an `include_object` filter in env.py.

Revision ID: 0002_platform
Revises: 0001_initial
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql as pg

revision = "0002_platform"
down_revision = "0001_initial"
branch_labels = None
depends_on = None

SCHEMAS = ["client", "reference", "portfolio", "trading", "performance", "compliance"]


def _uuid_pk() -> sa.Column:
    return sa.Column("id", pg.UUID(as_uuid=True), primary_key=True)


def _ts(name: str, **kw) -> sa.Column:
    return sa.Column(name, sa.DateTime(timezone=True), **kw)


def upgrade() -> None:
    for s in SCHEMAS:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{s}"')

    # ===================== CLIENT =====================
    op.create_table(
        "clients",
        _uuid_pk(),
        sa.Column(
            "onboarding_application_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("onboarding_applications.id"),
            nullable=False,
        ),
        sa.Column("client_code", sa.String(20), nullable=False),
        sa.Column("pan_hash", sa.String(64), nullable=False),
        sa.Column("pan_enc", sa.Text(), nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default="active"),
        sa.Column("investor_type", sa.String(20), nullable=False),
        sa.Column("full_name", sa.String(200), nullable=False),
        sa.Column("email", sa.String(254), nullable=False),
        sa.Column("mobile", sa.String(20), nullable=False),
        _ts("created_at", nullable=False),
        _ts("updated_at", nullable=False),
        sa.UniqueConstraint("client_code", name="uq_clients_client_code"),
        sa.UniqueConstraint("pan_hash", name="uq_clients_pan_hash"),
        sa.UniqueConstraint("onboarding_application_id", name="uq_clients_onboarding_app"),
        schema="client",
    )
    op.create_table(
        "client_bank_accounts",
        _uuid_pk(),
        sa.Column("client_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("client.clients.id", ondelete="CASCADE"), nullable=False),
        sa.Column("account_enc", sa.Text(), nullable=False),
        sa.Column("ifsc", sa.String(11), nullable=False),
        sa.Column("holder_name", sa.String(200), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False, server_default=sa.true()),
        _ts("created_at", nullable=False),
        schema="client",
    )
    op.create_table(
        "client_demat_accounts",
        _uuid_pk(),
        sa.Column("client_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("client.clients.id", ondelete="CASCADE"), nullable=False),
        sa.Column("bo_id", sa.String(16), nullable=False),
        sa.Column("depository", sa.String(4), nullable=False),
        _ts("created_at", nullable=False),
        schema="client",
    )
    op.create_table(
        "nominees",
        _uuid_pk(),
        sa.Column("client_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("client.clients.id", ondelete="CASCADE"), nullable=False),
        sa.Column("name_enc", sa.Text(), nullable=False),
        sa.Column("relationship", sa.String(40)),
        sa.Column("share_percent", sa.Numeric(5, 2), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        _ts("created_at", nullable=False),
        sa.CheckConstraint("rank between 1 and 3", name="ck_nominee_rank"),
        schema="client",
    )
    op.create_table(
        "client_risk_profiles",
        _uuid_pk(),
        sa.Column("client_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("client.clients.id", ondelete="CASCADE"), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(20), nullable=False),
        sa.Column("ruleset_version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("effective_from", sa.Date(), nullable=False),
        _ts("created_at", nullable=False),
        schema="client",
    )

    # ===================== REFERENCE =====================
    op.create_table(
        "securities_master",
        _uuid_pk(),
        sa.Column("isin", sa.String(12), nullable=False),
        sa.Column("symbol", sa.String(32), nullable=False),
        sa.Column("exchange", sa.String(10), nullable=False),
        sa.Column("instrument_type", sa.String(20), nullable=False),
        sa.Column("sector", sa.String(64)),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.UniqueConstraint("isin", name="uq_securities_isin"),
        schema="reference",
    )
    op.create_table(
        "benchmarks",
        _uuid_pk(),
        sa.Column("name", sa.String(80), nullable=False),
        sa.Column("code", sa.String(32), nullable=False),
        sa.UniqueConstraint("code", name="uq_benchmarks_code"),
        schema="reference",
    )
    op.create_table(
        "benchmark_values",
        _uuid_pk(),
        sa.Column("benchmark_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("reference.benchmarks.id", ondelete="CASCADE"), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("index_level", sa.Numeric(18, 4), nullable=False),
        sa.UniqueConstraint("benchmark_id", "as_of", name="uq_benchmark_value"),
        schema="reference",
    )
    op.create_table(
        "strategies",
        _uuid_pk(),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("code", sa.String(32), nullable=False),
        sa.Column("approach", sa.String(40), nullable=False),
        sa.Column("benchmark_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("reference.benchmarks.id"), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.UniqueConstraint("code", name="uq_strategies_code"),
        schema="reference",
    )
    op.create_table(
        "strategy_constituents",
        _uuid_pk(),
        sa.Column("strategy_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("reference.strategies.id", ondelete="CASCADE"), nullable=False),
        sa.Column("security_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("reference.securities_master.id"), nullable=False),
        sa.Column("target_weight", sa.Numeric(6, 4), nullable=False),
        sa.UniqueConstraint("strategy_id", "security_id", name="uq_strategy_constituent"),
        schema="reference",
    )
    op.create_table(
        "corporate_actions",
        _uuid_pk(),
        sa.Column("security_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("reference.securities_master.id"), nullable=False),
        sa.Column("action_type", sa.String(20), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("record_date", sa.Date()),
        sa.Column("ratio_or_amount", sa.Numeric(18, 6), nullable=False),
        schema="reference",
    )
    op.create_table(
        "brokers",
        _uuid_pk(),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("sebi_reg_no", sa.String(40), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.UniqueConstraint("sebi_reg_no", name="uq_brokers_sebi_reg"),
        schema="reference",
    )

    # ===================== PORTFOLIO =====================
    op.create_table(
        "fee_schedules",
        _uuid_pk(),
        sa.Column("name", sa.String(80), nullable=False),
        sa.Column("mgmt_fee_pct", sa.Numeric(5, 2), nullable=False),
        sa.Column("perf_fee_pct", sa.Numeric(5, 2), nullable=False, server_default="0"),
        sa.Column("high_water_mark", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("hurdle_rate_pct", sa.Numeric(5, 2)),
        schema="portfolio",
    )
    op.create_table(
        "portfolio_accounts",
        _uuid_pk(),
        sa.Column("client_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("client.clients.id"), nullable=False),
        sa.Column("strategy_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("reference.strategies.id"), nullable=False),
        sa.Column("demat_account_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("client.client_demat_accounts.id"), nullable=True),
        sa.Column("fee_schedule_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("portfolio.fee_schedules.id"), nullable=True),
        sa.Column("account_code", sa.String(20), nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default="active"),
        sa.Column("inception_date", sa.Date(), nullable=False),
        _ts("created_at", nullable=False),
        sa.UniqueConstraint("account_code", name="uq_portfolio_account_code"),
        schema="portfolio",
    )
    op.create_table(
        "capital_flows",
        _uuid_pk(),
        sa.Column("portfolio_account_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("portfolio.portfolio_accounts.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("flow_type", sa.String(16), nullable=False),
        sa.Column("asset_kind", sa.String(12), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("value_date", sa.Date(), nullable=False),
        _ts("created_at", nullable=False),
        schema="portfolio",
    )
    op.create_table(
        "cash_ledger",
        _uuid_pk(),
        sa.Column("portfolio_account_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("portfolio.portfolio_accounts.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("entry_type", sa.String(24), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("balance_paise", sa.BigInteger(), nullable=False),
        sa.Column("posted_on", sa.Date(), nullable=False),
        _ts("created_at", nullable=False),
        schema="portfolio",
    )
    op.create_table(
        "holdings",
        _uuid_pk(),
        sa.Column("portfolio_account_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("portfolio.portfolio_accounts.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("security_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("reference.securities_master.id"), nullable=False),
        sa.Column("quantity", sa.Numeric(20, 4), nullable=False),
        sa.Column("avg_cost_paise", sa.BigInteger(), nullable=False),
        _ts("updated_at", nullable=False),
        sa.UniqueConstraint("portfolio_account_id", "security_id", name="uq_holding"),
        schema="portfolio",
    )
    op.create_table(
        "holding_lots",
        _uuid_pk(),
        sa.Column("holding_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("portfolio.holdings.id", ondelete="CASCADE"), nullable=False),
        sa.Column("quantity", sa.Numeric(20, 4), nullable=False),
        sa.Column("cost_paise", sa.BigInteger(), nullable=False),
        sa.Column("acquired_on", sa.Date(), nullable=False),
        schema="portfolio",
    )

    # ===================== TRADING =====================
    op.create_table(
        "orders",
        _uuid_pk(),
        sa.Column("strategy_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("reference.strategies.id"), nullable=False),
        sa.Column("security_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("reference.securities_master.id"), nullable=False),
        sa.Column("side", sa.String(4), nullable=False),
        sa.Column("quantity", sa.Numeric(20, 4), nullable=False),
        sa.Column("order_type", sa.String(12), nullable=False, server_default="market"),
        sa.Column("limit_price_paise", sa.BigInteger()),
        sa.Column("status", sa.String(16), nullable=False, server_default="new"),
        _ts("created_at", nullable=False),
        schema="trading",
    )
    op.create_table(
        "order_allocations",
        _uuid_pk(),
        sa.Column("order_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("trading.orders.id", ondelete="CASCADE"), nullable=False),
        sa.Column("portfolio_account_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("portfolio.portfolio_accounts.id"), nullable=False),
        sa.Column("allocated_qty", sa.Numeric(20, 4), nullable=False),
        sa.UniqueConstraint("order_id", "portfolio_account_id", name="uq_order_allocation"),
        schema="trading",
    )
    op.create_table(
        "trades",
        _uuid_pk(),
        sa.Column("order_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("trading.orders.id"), nullable=True),
        sa.Column("portfolio_account_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("portfolio.portfolio_accounts.id"), nullable=False),
        sa.Column("security_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("reference.securities_master.id"), nullable=False),
        sa.Column("broker_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("reference.brokers.id"), nullable=False),
        sa.Column("side", sa.String(4), nullable=False),
        sa.Column("quantity", sa.Numeric(20, 4), nullable=False),
        sa.Column("price_paise", sa.BigInteger(), nullable=False),
        _ts("traded_at", nullable=False),
        sa.Column("contract_note", sa.String(64)),
        _ts("created_at", nullable=False),
        schema="trading",
    )

    # ===================== PERFORMANCE =====================
    op.create_table(
        "valuation_snapshots",
        _uuid_pk(),
        sa.Column("portfolio_account_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("portfolio.portfolio_accounts.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("market_value_paise", sa.BigInteger(), nullable=False),
        sa.Column("cost_value_paise", sa.BigInteger(), nullable=False),
        sa.Column("cash_paise", sa.BigInteger(), nullable=False, server_default="0"),
        sa.UniqueConstraint("portfolio_account_id", "as_of", name="uq_valuation_snapshot"),
        schema="performance",
    )
    op.create_table(
        "performance_returns",
        _uuid_pk(),
        sa.Column("portfolio_account_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("portfolio.portfolio_accounts.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("period", sa.String(8), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("twrr_pct", sa.Numeric(9, 4), nullable=False),
        sa.Column("benchmark_pct", sa.Numeric(9, 4)),
        schema="performance",
    )
    op.create_table(
        "statements",
        _uuid_pk(),
        sa.Column("portfolio_account_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("portfolio.portfolio_accounts.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("period", sa.String(16), nullable=False),
        sa.Column("storage_key", sa.String(512), nullable=False),
        sa.Column("sha256", sa.String(64), nullable=False),
        _ts("generated_at", nullable=False),
        schema="performance",
    )

    # ===================== COMPLIANCE =====================
    op.create_table(
        "compliance_reviews",
        _uuid_pk(),
        sa.Column("client_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("client.clients.id"), nullable=True),
        sa.Column("portfolio_account_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("portfolio.portfolio_accounts.id"), nullable=True),
        sa.Column("review_type", sa.String(24), nullable=False),
        sa.Column("outcome", sa.String(16), nullable=False, server_default="pending"),
        sa.Column("maker", sa.String(120), nullable=False),
        sa.Column("checker", sa.String(120)),
        sa.Column("notes", sa.Text()),
        _ts("created_at", nullable=False),
        schema="compliance",
    )
    op.create_table(
        "suitability_assessments",
        _uuid_pk(),
        sa.Column("risk_profile_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("client.client_risk_profiles.id"), nullable=False),
        sa.Column("portfolio_account_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("portfolio.portfolio_accounts.id"), nullable=False),
        sa.Column("is_suitable", sa.Boolean(), nullable=False),
        sa.Column("rationale", sa.Text()),
        _ts("assessed_at", nullable=False),
        schema="compliance",
    )
    op.create_table(
        "compliance_alerts",
        _uuid_pk(),
        sa.Column("portfolio_account_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("portfolio.portfolio_accounts.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("rule", sa.String(32), nullable=False),
        sa.Column("severity", sa.String(12), nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default="open"),
        sa.Column("details", pg.JSONB(), nullable=False, server_default="{}"),
        _ts("raised_at", nullable=False),
        schema="compliance",
    )


def downgrade() -> None:
    for s in reversed(SCHEMAS):
        op.execute(f'DROP SCHEMA IF EXISTS "{s}" CASCADE')
